Updated CloudWatch Logs
mpostument/awstaghelper pull request #223
Opened 2024-10-14 02:27 UTC by jaemokhong

The ListTagsLogGroup and TagLogGroup operations in AWS CloudWatch Logs are marked for deprecation, and AWS is encouraging the use of newer alternatives.
I have replaced the ListTagsLogGroup and TagLogGroup operations with the new API.
https://docs.aws.amazon.com/ko_kr/AmazonCloudWatchLogs/latest/APIReference/API_ListTagsLogGroup.html
https://docs.aws.amazon.com/ko_kr/AmazonCloudWatchLogs/latest/APIReference/API_TagLogGroup.html

2024-10-14 09:30 UTC, mpostument requested changes

2024-10-14 09:30 UTC, mpostument commented on cmd/cloudwatch.go
> +    "github.com/spf13/cobra"
Can you please run the formating?

2024-10-16 06:04 UTC, jaemokhong commented on cmd/cloudwatch.go
> +    "github.com/spf13/cobra"
I have completed it

2024-10-16 09:54 UTC, mpostument approved these changes

2024-10-16 09:54 UTC, merged

2024-10-16 11:42 UTC, mpostument commented
@jaemokhong this release contain your changes - https://github.com/mpostument/awstaghelper/releases/tag/0.20.3